### ISSUE TITLE
Custom Formatters

### ISSUE THREAD

**Issue by timmckenzie** [shouldjs/format#3]
Hi,

I am using Should for an internal testing framework.  We primarily do checks on [JSDOM] (https://github.com/tmpvar/jsdom) HTML DOM objects.  If we get a Should exception, the resulting AssertionError#message is typically around 5MB, which is way to big.  I would like to be able to define custom formatters for custom types in Should.  I can create a formatting function internal to our testing framework, but would prefer with to Should/format.  

I see that I can add custom formatters.  However, should/type does not have any method for adding custom types. Also in Should/type, the module.exports is overwritten with the getType method.  Changes to have custom types in should/type would cause breaking changes to Should.  

Are custom formatters and custom the type detection on the road map for Should?
Can they be added?
Would a pull request which breaks backward compatibility with should/type be accepted?

One more thing.  I really like using Should.  It has drastically reduced the complexity of our tests while making them much more readable.  Should is a fantastic project.

**Comment by btd** [comment]
hi

> Are custom formatters and custom the type detection on the road map for Should?

I actually do not think about it

> Can they be added?

Yes.

> Would a pull request which breaks backward compatibility with should/type be accepted?

Yes, should-type and should-format was written only for shouldjs purposes, so it is possible to break it as much as need)

> One more thing. I really like using Should. It has drastically reduced the complexity of our tests while making them much more readable. Should is a fantastic project.

Thanks)

**Comment by btd** [comment]
@timmckenzie i did small change in should-type to allow add custom types (anyway it is just array of functions so you can do anything you want with it).

**Comment by btd** [comment]
@timmckenzie i will close this one, as it does not active. In currect state type and format packages both allows customizations. Feel free to reopen this issue or open new, if you think something missing.
